In [1]:
import numpy as np

In [4]:
a=np.zeros(5)   #Return a new array of given shape and type, filled with zeros.

In [5]:
a

array([0., 0., 0., 0., 0.])

In [6]:
a.ndim

1

In [7]:
b=np.zeros(5,dtype=int) 

In [8]:
b

array([0, 0, 0, 0, 0])

In [11]:
a=np.zeros((3,4),dtype=int)

In [12]:
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [13]:
a.ndim

2

In [6]:
c= np.ones(5, dtype=int)

In [7]:
c

array([1, 1, 1, 1, 1])

In [13]:
k=np.ones((4,5),dtype=int)

In [14]:
k

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [15]:
np.array([[12,12,23,18],[24,25,26,27]])

array([[12, 12, 23, 18],
       [24, 25, 26, 27]])

In [16]:
# creating three dimension array 


In [17]:
# this is first dimension 
np.zeros(4,dtype=int)

array([0, 0, 0, 0])

In [18]:
# two dimension
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [20]:
# three dimension 
np.zeros((1,3,4)) # here 3 is row and 4 is colums and 1 is another dimension 

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [22]:
arr=np.zeros((3,4,5),dtype=int)

In [23]:
arr

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [24]:
arr.ndim

3

In [25]:
# create more dimension array
b=np.zeros((2,3,4,5),dtype=int)  # this is 4 dimension array ->> create more dimensios(n dimension) then np.zeros(n number of  element)

In [27]:
b

array([[[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]],


       [[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]]])

In [28]:
b.ndim

4

In [52]:
# create an array 
arr=np.zeros((3,4),dtype=int)

In [53]:
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [54]:
# now we want to add all element as 5 then 
arr1=arr+5

In [55]:
arr1

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [56]:
arr2=arr1+5

In [57]:
arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [61]:
arr3

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

In [63]:
arr3*2  # multiplication 

array([[24, 24, 24, 24],
       [24, 24, 24, 24],
       [24, 24, 24, 24]])

In [64]:
arr3-1

array([[11, 11, 11, 11],
       [11, 11, 11, 11],
       [11, 11, 11, 11]])

In [76]:
# identity matrix
identity=np.eye(3,3,dtype=int)  # Return a 2-D array with ones on the diagonal and zeros elsewhere.
# syntax:np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
# N :
"""int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array."""



'int\n  Number of rows in the output.\nM : int, optional\n  Number of columns in the output. If None, defaults to `N`.\nk : int, optional\n  Index of the diagonal: 0 (the default) refers to the main diagonal,\n  a positive value refers to an upper diagonal, and a negative value\n  to a lower diagonal.\ndtype : data-type, optional\n  Data-type of the returned array.'

In [77]:
identity

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [78]:
iden1=np.eye(5)

In [79]:
iden1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [94]:
# empty
em=np.empty((3,3))  # Return a new array of given shape and type, without initializing entries. it means it returns any value of given shape

In [95]:
em

array([[0.e+000, 0.e+000, 0.e+000],
       [0.e+000, 0.e+000, 1.e-320],
       [0.e+000, 0.e+000, 0.e+000]])

In [97]:
# optional >>> randomly
import random 
random.choice((2,3,4,5))

5

In [100]:
random.choice(("niki"))

'i'

In [102]:
random.choice((1.1,2.3,4.5))

4.5

In [104]:
random.randrange(1,10) # it returns random number in random range 

8

In [108]:
# if you want to suffle the list then 
lis=[1,2,3,4,5,6,7,8,9,10]
random.shuffle(lis)

In [109]:
lis

[4, 6, 10, 8, 5, 3, 2, 1, 7, 9]

In [110]:
random.randrange(7,14)

10

In [111]:
random.uniform(7,14)

9.973254164322086

In [112]:
# random number related concept in numpy 

In [114]:
np.array([])

array([], dtype=float64)

In [115]:
np.random.random_sample()

0.25147643450780455

In [117]:
np.random.random_sample((5,)) # it returns 1D array of 5 values

array([0.42270899, 0.82365656, 0.87722629, 0.57948249, 0.21404265])

In [147]:
np.random.rand(2,3) # it returns 2Darray of 2 X 3 size

array([[0.0238925 , 0.79300861, 0.10682123],
       [0.86233951, 0.9351369 , 0.61018146]])

In [122]:
# it returns standard normal distribution 
# randn() >>>> Return a sample (or samples) from the "standard normal" distribution.
np.random.randn(2,4)

array([[ 0.1445628 ,  0.54740604, -0.10898215, -2.22632613],
       [ 0.1756214 ,  0.06680214, -0.21806241,  0.02709715]])

In [125]:
arr=np.random.randint(1,6,size=(3,4)) # here 1 and 6 is the range and (3,4) is the row and column >> it returns 3 X 4 matrix of range 1 to 6 

In [126]:
arr

array([[1, 3, 2, 1],
       [3, 5, 1, 5],
       [1, 5, 3, 2]])

In [127]:
arr.ndim

2

In [129]:
arr.shape

(3, 4)

In [130]:
arr.size

12

In [131]:
# reshaping the array
a1=np.array([[1,2,3],[4,5,6]])

In [132]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [134]:
a1.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [135]:
# another ex:
arr=np.random.randint(1,6,size=(3,4))

In [136]:
arr

array([[2, 2, 5, 1],
       [2, 5, 2, 5],
       [3, 3, 5, 1]])

In [143]:
arr1=arr.reshape(2,6) # Returns an array containing the same data with a new shape.

In [145]:
arr1 #  if array size ==reshape array size then possible  means arr size=12 so reshape size must be 12 

array([[2, 2, 5, 1, 2, 5],
       [2, 5, 3, 3, 5, 1]])

In [146]:
arr1=arr.reshape(2,8) # if here we use 2,8 then total no of element is 16 but inside arr 12 element present thats why error

ValueError: cannot reshape array of size 12 into shape (2,8)

In [149]:
arr.reshape(2,2) # here current array size is 4 but main array size is 12 so error

ValueError: cannot reshape array of size 12 into shape (2,2)

In [152]:
# case when you do not khow in reshape what should be the raw and column count 
# then use any negative value for rows and column 
arr.reshape(4,-1)# here we dont know the column count 

array([[2, 2, 5],
       [1, 2, 5],
       [2, 5, 3],
       [3, 5, 1]])

In [153]:
arr.reshape(-1,3) # here we dont know the row count 

array([[2, 2, 5],
       [1, 2, 5],
       [2, 5, 3],
       [3, 5, 1]])

In [155]:
 # if you want to see the original array then 
arr.reshape(2,6).base # here you have to pass any argument 

array([[2, 2, 5, 1],
       [2, 5, 2, 5],
       [3, 3, 5, 1]])

In [158]:
arr.reshape(-1,6).base # here argument can be anything

array([[2, 2, 5, 1],
       [2, 5, 2, 5],
       [3, 3, 5, 1]])

In [159]:
arr.size

12

In [160]:
# reshape it into more dimension 
arr.reshape(2,2,3)  # always remember multiplication must be equal to array size
# (2 x 2 x 3)=12 is array size(true)

array([[[2, 2, 5],
        [1, 2, 5]],

       [[2, 5, 3],
        [3, 5, 1]]])

In [161]:
# another way 
arr.reshape(3,2,2)

array([[[2, 2],
        [5, 1]],

       [[2, 5],
        [2, 5]],

       [[3, 3],
        [5, 1]]])

In [163]:
#another way 
arr.reshape(4,1,3)

array([[[2, 2, 5]],

       [[1, 2, 5]],

       [[2, 5, 3]],

       [[3, 5, 1]]])

In [164]:
#another way 
arr.reshape(1,2,2,3)

array([[[[2, 2, 5],
         [1, 2, 5]],

        [[2, 5, 3],
         [3, 5, 1]]]])

In [165]:
arr.reshape(1,2,2,3).ndim

4

In [167]:
arr.reshape(4,3,1) # three rows and 1 column repeat it four times 

array([[[2],
        [2],
        [5]],

       [[1],
        [2],
        [5]],

       [[2],
        [5],
        [3]],

       [[3],
        [5],
        [1]]])

In [2]:
# conditions on array 
arr1=np.random.randint(1,10,size=(5,6))

In [3]:
arr1

array([[4, 6, 4, 3, 8, 6],
       [5, 2, 2, 2, 5, 7],
       [6, 2, 2, 1, 1, 4],
       [9, 2, 9, 3, 3, 5],
       [1, 3, 4, 9, 3, 5]])

In [7]:
arr1.shape

(5, 6)

In [8]:
arr1.size

30

In [9]:
arr1.ndim

2

In [10]:
 # now check the arr condition 
# first confition element >3
arr2=arr1>3

In [11]:
arr2

array([[ True,  True,  True, False,  True,  True],
       [ True, False, False, False,  True,  True],
       [ True, False, False, False, False,  True],
       [ True, False,  True, False, False,  True],
       [False, False,  True,  True, False,  True]])

In [12]:
arr1[arr1>3]

array([4, 6, 4, 8, 6, 5, 5, 7, 6, 4, 9, 9, 5, 4, 9, 5])

In [13]:
arr1[arr1<3]

array([2, 2, 2, 2, 2, 1, 1, 2, 1])

In [14]:
arr1

array([[4, 6, 4, 3, 8, 6],
       [5, 2, 2, 2, 5, 7],
       [6, 2, 2, 1, 1, 4],
       [9, 2, 9, 3, 3, 5],
       [1, 3, 4, 9, 3, 5]])

In [15]:
# acessing element of an array
arr1[0]

array([4, 6, 4, 3, 8, 6])

In [16]:
arr1[1]

array([5, 2, 2, 2, 5, 7])

In [18]:
arr1[3]

array([9, 2, 9, 3, 3, 5])

In [19]:
arr1[3][2]

9

In [20]:
arr1[4]

array([1, 3, 4, 9, 3, 5])

In [21]:
arr1[4][4]

3

In [25]:
# you want to access 0th row to 3rd row
arr1[0:4] # here 4 is exclusive

array([[4, 6, 4, 3, 8, 6],
       [5, 2, 2, 2, 5, 7],
       [6, 2, 2, 1, 1, 4],
       [9, 2, 9, 3, 3, 5]])

In [28]:
# if you want to jump as 0th row then 2nd row then 4th row then
arr1[0:4:2]   # slicing the array

array([[4, 6, 4, 3, 8, 6],
       [6, 2, 2, 1, 1, 4]])

In [33]:
# if you want to access 0th to 2nd row and 0th column and 3rd column
arr1[0:3,[0,3]] # when you want to access specific column then [column1,column2] here column1 is 0th and column2 is 3rd column 

array([[4, 3],
       [5, 2],
       [6, 1]])

In [30]:
# slicing of both rows and column 
arr1

array([[4, 6, 4, 3, 8, 6],
       [5, 2, 2, 2, 5, 7],
       [6, 2, 2, 1, 1, 4],
       [9, 2, 9, 3, 3, 5],
       [1, 3, 4, 9, 3, 5]])

In [32]:
# want 0 to 3rd row and 1 to 3rd column
arr1[0:4,1:4] 

array([[6, 4, 3],
       [2, 2, 2],
       [2, 2, 1],
       [2, 9, 3]])

In [34]:
arr1[2:4,[1,4]] 

array([[2, 1],
       [2, 3]])

In [39]:
# mathmatical operation between two arrays
arr1=np.random.randint(1,3,(3,3)) # means in between 1 to 3 (exclusive) matrix will be filled 
arr2=np.random.randint(1,4,(3,3))

In [40]:
arr1

array([[1, 1, 2],
       [2, 2, 2],
       [2, 1, 1]])

In [41]:
arr2

array([[1, 3, 3],
       [3, 1, 2],
       [2, 3, 2]])

In [47]:
add=arr1+arr2  # index wise addition 

In [44]:
add

array([[2, 4, 5],
       [5, 3, 4],
       [4, 4, 3]])

In [54]:
mul=arr1*arr2  #index wise multiplication not matrix multiplication

In [55]:
mul

array([[1, 3, 6],
       [6, 2, 4],
       [4, 3, 2]])

In [50]:
sub=arr2-arr1

In [51]:
sub

array([[ 0,  2,  1],
       [ 1, -1,  0],
       [ 0,  2,  1]])

In [52]:
sub1=arr1-arr2

In [53]:
sub1

array([[ 0, -2, -1],
       [-1,  1,  0],
       [ 0, -2, -1]])

In [56]:
# index wise division 
arr1/arr2

array([[1.        , 0.33333333, 0.66666667],
       [0.66666667, 2.        , 1.        ],
       [1.        , 0.33333333, 0.5       ]])

In [57]:
# divide by zero 
arr1/0

C:\Users\kalya\AppData\Local\Temp\ipykernel_12928\2960180225.py:2: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [58]:
# matrix multiplicationn : specialiased from 2-D array 
# it different from matrix index wise multiplication
# for matrix chain multiplication we use " @ "
arr1 @ arr2

array([[ 8, 10,  9],
       [12, 14, 14],
       [ 7, 10, 10]])

In [59]:
# index multiplication 
arr1 * arr2

array([[1, 3, 6],
       [6, 2, 4],
       [4, 3, 2]])

In [60]:
# condition for matrix multiplication is no of column is equal to no of row of another matrix 
# 3 X 4 and 4 X 3 ,here 4 and 4 is equal 
# and the result matrix will be 3 X 3 means if a X b and b X a are two matrix then result matrix will be a X c

In [61]:
# ANOTHER CONCEPT BROADCASTING
arr=np.zeros((3,4))

In [62]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [63]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [64]:
arr+[1,2,3,4]

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [65]:
a=np.array([1,2,3,4])

In [66]:
a

array([1, 2, 3, 4])

In [67]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [72]:
# another concept is TRANSPOSE  >> IT converts rows to column and column to rows
# it can transpose the 2-D arrays on the other hand it has no effect on 1-D array
# byusing " T " we transpose the data 
arr2=np.random.randint(1,5,(3,4))


In [73]:
arr2

array([[2, 3, 4, 3],
       [1, 3, 2, 1],
       [3, 1, 2, 3]])

In [74]:
arr2.T

array([[2, 1, 3],
       [3, 3, 1],
       [4, 2, 2],
       [3, 1, 3]])

In [75]:
a=np.array([[1,2,3,4],[2,5,6,7],[11,12,13,14]])

In [76]:
a

array([[ 1,  2,  3,  4],
       [ 2,  5,  6,  7],
       [11, 12, 13, 14]])

In [77]:
a.T

array([[ 1,  2, 11],
       [ 2,  5, 12],
       [ 3,  6, 13],
       [ 4,  7, 14]])