In [3]:
# numpy stands fot neumarical python >>>>>> The fundamental package for scientific computing with Python
# 2005 by travis oliphant
# before 2005 there were special mathmatical tools (similar to tora , linga)

In [1]:
import numpy as np  # here as is alias ( means we call the numpy library as np)

In [2]:
np.__version__

'1.26.4'

In [6]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [7]:
# numpy store the data in a numpy array >>> means it store the data in a homogeneous way 
# already we have list but why numpy ?
# ->> numpy is bulit using c and c is one of the faster language thats why numpy computation is fast 
# why fast ?
# because it store homogeneous data 

In [8]:
l=[1,2,3,4,5]

In [9]:
arr=np.array(l)

In [10]:
arr

array([1, 2, 3, 4, 5])

In [11]:
type(arr)

numpy.ndarray

In [14]:
l=[1,2,3,4,5,"ajay"]  
arr1=np.array(l)  # here no error occurs because numpy array store all value as string 

In [13]:
arr1

array(['1', '2', '3', '4', '5', 'ajay'], dtype='<U11')

In [15]:
l=[1,2,3,4.2,5,"ajay"]
arr2=np.array(l) 

In [16]:
arr2

array(['1', '2', '3', '4.2', '5', 'ajay'], dtype='<U32')

In [17]:
l=[1,2,3,4.2,5,"ajay",True]
arr3=np.array(l) 

In [18]:
arr3

array(['1', '2', '3', '4.2', '5', 'ajay', 'True'], dtype='<U32')

In [21]:
arr3.ndim   # ndim calculate the dimenssion 

1

In [22]:
arr=np.array([[1,2,3],[4,5,6]])
arr.ndim

2

In [23]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
# matrix : matrix is a specialised array of two dimenssion  
mat=np.matrix([1,2,3,4.2,5,"ajay"])

In [5]:
mat

matrix([['1', '2', '3', '4.2', '5', 'ajay']], dtype='<U32')

In [6]:
type(mat)

numpy.matrix

In [7]:
mat2=np.matrix([[1,2,3],[4,5,6]])

In [8]:
mat2

matrix([[1, 2, 3],
        [4, 5, 6]])

In [11]:
# we cannot write the matrix as three dimenssion 
mat3=np.matrix([[[1,2,3],[4,5,6],[7,8,9]]])  # it will throw error because matrix must be 2-dimensional

ValueError: matrix must be 2-dimensional

In [12]:
# if we put the three dimenssion inside the array then no error occurs 
arr3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])  

In [13]:
arr3  # array can be multi_dimensional 

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [15]:
arr3.ndim

3

In [16]:
# more ways to convert in array 
l=[1,2,3,4]
np.asarray(l)  # this is the initial function to convert into an array then np.arry come 

array([1, 2, 3, 4])

In [17]:
# another way 
np.asanyarray(l) 

array([1, 2, 3, 4])

In [18]:
# asanyarray will convert the input to an ndarray ,but pass ndarray subclasses through.
mat

matrix([['1', '2', '3', '4.2', '5', 'ajay']], dtype='<U32')

In [20]:
np.asanyarray(mat) # same no change matrix can not change into an array 

matrix([['1', '2', '3', '4.2', '5', 'ajay']], dtype='<U32')

In [21]:
# tuple->> array
tup=(1,2,3)
type(tup)

tuple

In [22]:
np.array(tup)

array([1, 2, 3])

In [23]:
tup=([[1,2,3],[4,5,6]])

In [28]:
arr=np.array(tup)

In [29]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
arr[0][0]

1

In [34]:
arr[1][2]

6

In [38]:
# shallow copy and deep copy 
l=[1,2,3,4,5,6]
arr=np.array(l)

In [39]:
arr

array([1, 2, 3, 4, 5, 6])

In [40]:
arr[0]=1000

In [41]:
arr

array([1000,    2,    3,    4,    5,    6])

In [42]:
a=arr # shallow 

In [43]:
a

array([1000,    2,    3,    4,    5,    6])

In [44]:
arr

array([1000,    2,    3,    4,    5,    6])

In [45]:
arr[0]=500

In [46]:
arr

array([500,   2,   3,   4,   5,   6])

In [47]:
a

array([500,   2,   3,   4,   5,   6])

In [48]:
# deepcopy
# create a copy 
b= arr.copy()

In [49]:
b

array([500,   2,   3,   4,   5,   6])

In [50]:
b[0]=100

In [51]:
b

array([100,   2,   3,   4,   5,   6])

In [52]:
arr

array([500,   2,   3,   4,   5,   6])

In [54]:
# multiple approach to generate any array 
arr1=np.fromfunction(lambda i,j:i==j,(3,3)) # constract a array by executing a function over each co-ordinate 

In [55]:
arr1

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [56]:
arr1.ndim

2

In [60]:
arr1.shape # shape of the matrix

(3, 3)

In [61]:
arr1.size # total no 

9

In [62]:
# another function 
arr2=np.fromfunction(lambda i,j:i*j,(3,3))

In [63]:
arr2

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [64]:
arr2.shape

(3, 3)

In [65]:
arr2.size

9

In [66]:
arr2.ndim

2

In [67]:
for i in range(5):
    print(i)

0
1
2
3
4


In [72]:
[ i for i in range(5)]

[0, 1, 2, 3, 4]

In [93]:
list((i for i in range(5)))

[0, 1, 2, 3, 4]

In [94]:
iterator=(i for i in range (5))

In [95]:
iterator

<generator object <genexpr> at 0x0000021E41C2ECF0>

In [96]:
ans=np.fromiter(iterator,int) 


In [98]:
ans   # # Create a new 1-dimensional array from an iterable object.

array([0, 1, 2, 3, 4])

In [100]:
# another ex:
np.fromstring(" 22 23 25",sep=" ",dtype=int)    # A new 1-D array initialized from text data in a string.


array([22, 23, 25])

In [101]:
# now work in string 
str="ajay,bijoy,sanjay"
str.split(",")

['ajay', 'bijoy', 'sanjay']

In [103]:
np.array(str.split(","))

array(['ajay', 'bijoy', 'sanjay'], dtype='<U6')

In [105]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [108]:
# to do the above work numpy has 
np.arange(1,10) # arange returns evenly specified value within a given interval
# syntax :arange([start, stop, step] stop=range-1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
np.arange(1,10,0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [111]:
np.arange(1,10,0.4)

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. , 5.4, 5.8,
       6.2, 6.6, 7. , 7.4, 7.8, 8.2, 8.6, 9. , 9.4, 9.8])

In [112]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [115]:
# another method 
np.linspace(1,5,10) # this method returns specific times  of number (here you given 10) into the given range means in this example this method returns 10 numbers of range 1 to 5 

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])