In [1]:
import numpy as np

In [3]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [4]:
arr1

array([[1, 2, 2],
       [2, 2, 2],
       [2, 2, 1]])

In [5]:
arr2

array([[1, 1, 1],
       [2, 1, 1],
       [2, 1, 1]])

In [6]:
# fallen the array 
arr1.flatten()  # Return a copy of the array collapsed into one dimension.

array([1, 2, 2, 2, 2, 2, 2, 2, 1])

In [7]:
arr2.flatten()

array([1, 1, 1, 2, 1, 1, 2, 1, 1])

In [8]:
# expand dimension 
arr=np.array([1,2,3,4])

In [9]:
arr

array([1, 2, 3, 4])

In [10]:
arr.ndim

1

In [11]:
np.expand_dims(arr,axis=0) # syntax:np.expand_dims(a, axis)  here a is array name that you want to expand if axis=0 then row wise expand if axis=1 then column wise expand
#Expand the shape of an array.
#Insert a new axis that will appear at the `axis` position in the expandedarray shape.

array([[1, 2, 3, 4]])

In [12]:
np.expand_dims(arr,axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [13]:
 np.expand_dims(arr,axis=1).ndim # previously it's dimension is 1 but now 2 .means expand the dimension


2

In [14]:
# expanding 2D to 3D
arr=np.random.randint(1,3,(3,4))

In [15]:
arr

array([[2, 1, 2, 1],
       [2, 1, 1, 1],
       [2, 2, 2, 2]])

In [16]:
a=np.expand_dims(arr,axis=1) # here column wise expand

In [24]:
a

array([[[1, 1, 1, 1]],

       [[2, 2, 2, 1]],

       [[2, 2, 1, 1]]])

In [17]:
b=np.expand_dims(arr,axis=0)  #here row wise expand

In [18]:
b

array([[[2, 1, 2, 1],
        [2, 1, 1, 1],
        [2, 2, 2, 2]]])

In [27]:
a.flatten()

array([1, 1, 1, 1, 2, 2, 2, 1, 2, 2, 1, 1])

In [28]:
b.flatten()

array([1, 1, 1, 1, 2, 2, 2, 1, 2, 2, 1, 1])

In [29]:
ar=np.array([[1],[2],[3]])

In [31]:
ar

array([[1],
       [2],
       [3]])

In [32]:
ar.ndim

2

In [36]:
am=np.expand_dims(ar,axis=0)

In [35]:
np.expand_dims(ar,axis=0).ndim

3

In [37]:
am

array([[[1],
        [2],
        [3]]])

In [38]:
am.flatten()

array([1, 2, 3])

In [43]:
# squeezing the dimension
np.squeeze(am)  #Remove axes of length one from `a`.

array([1, 2, 3])

In [41]:
np.squeeze(b) 

array([[1, 1, 1, 1],
       [2, 2, 2, 1],
       [2, 2, 1, 1]])

In [42]:
b.flatten()

array([1, 1, 1, 1, 2, 2, 2, 1, 2, 2, 1, 1])

In [44]:
# difference between squeeze() and flatten 
# : matrix dimension reduced by 1 meand akta dimension kombe but flatten a 1D array print korbe 

In [49]:
# repeat function  syntax:.repeat(arrayname that you want to repeat,how many times you want to repeat,axis= 0 or 1) by default axis is none 
np.repeat(am,3) # Repeat each element of an array after themselves

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [50]:
np.repeat(b,2,axis=0)

array([[[1, 1, 1, 1],
        [2, 2, 2, 1],
        [2, 2, 1, 1]],

       [[1, 1, 1, 1],
        [2, 2, 2, 1],
        [2, 2, 1, 1]]])

In [51]:
np.repeat(b,2,axis=1)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [2, 2, 2, 1],
        [2, 2, 2, 1],
        [2, 2, 1, 1],
        [2, 2, 1, 1]]])

In [22]:
# shifting place  
s=np.roll(b,-1)# Roll array elements along a given axis.
#Elements that roll beyond the last position are re-introduced at the first.
#
"""
Examples
--------
>>> x = np.arange(10)
>>> np.roll(x, 2)
array([8, 9, 0, 1, 2, 3, 4, 5, 6, 7])
>>> np.roll(x, -2)
array([2, 3, 4, 5, 6, 7, 8, 9, 0, 1])

>>> x2 = np.reshape(x, (2, 5))
>>> x2
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])
>>> np.roll(x2, 1)
array([[9, 0, 1, 2, 3],
       [4, 5, 6, 7, 8]])
>>> np.roll(x2, -1)
array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])
>>> np.roll(x2, 1, axis=0)
array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])
>>> np.roll(x2, -1, axis=0)
array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])
>>> np.roll(x2, 1, axis=1)
array([[4, 0, 1, 2, 3],
       [9, 5, 6, 7, 8]])
>>> np.roll(x2, -1, axis=1)
array([[1, 2, 3, 4, 0],
       [6, 7, 8, 9, 5]])
>>> np.roll(x2, (1, 1), axis=(1, 0))
array([[9, 5, 6, 7, 8],
       [4, 0, 1, 2, 3]])
>>> np.roll(x2, (2, 1), axis=(1, 0))
array([[8, 9, 5, 6, 7],
       [3, 4, 0, 1, 2]])
       """
# above are example of roll 

'\nExamples\n--------\n>>> x = np.arange(10)\n>>> np.roll(x, 2)\narray([8, 9, 0, 1, 2, 3, 4, 5, 6, 7])\n>>> np.roll(x, -2)\narray([2, 3, 4, 5, 6, 7, 8, 9, 0, 1])\n\n>>> x2 = np.reshape(x, (2, 5))\n>>> x2\narray([[0, 1, 2, 3, 4],\n       [5, 6, 7, 8, 9]])\n>>> np.roll(x2, 1)\narray([[9, 0, 1, 2, 3],\n       [4, 5, 6, 7, 8]])\n>>> np.roll(x2, -1)\narray([[1, 2, 3, 4, 5],\n       [6, 7, 8, 9, 0]])\n>>> np.roll(x2, 1, axis=0)\narray([[5, 6, 7, 8, 9],\n       [0, 1, 2, 3, 4]])\n>>> np.roll(x2, -1, axis=0)\narray([[5, 6, 7, 8, 9],\n       [0, 1, 2, 3, 4]])\n>>> np.roll(x2, 1, axis=1)\narray([[4, 0, 1, 2, 3],\n       [9, 5, 6, 7, 8]])\n>>> np.roll(x2, -1, axis=1)\narray([[1, 2, 3, 4, 0],\n       [6, 7, 8, 9, 5]])\n>>> np.roll(x2, (1, 1), axis=(1, 0))\narray([[9, 5, 6, 7, 8],\n       [4, 0, 1, 2, 3]])\n>>> np.roll(x2, (2, 1), axis=(1, 0))\narray([[8, 9, 5, 6, 7],\n       [3, 4, 0, 1, 2]])\n       '

In [23]:
s

array([[[1, 2, 1, 2],
        [1, 1, 1, 2],
        [2, 2, 2, 2]]])

In [24]:
c= np.array([[1,2],[3,4],[5,6],[7,8]])

In [25]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [26]:
np.roll(c,-1)

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 1]])

In [27]:
np.roll(c,-1,axis=0)

array([[3, 4],
       [5, 6],
       [7, 8],
       [1, 2]])

In [28]:
np.roll(c,-1,axis=1)

array([[2, 1],
       [4, 3],
       [6, 5],
       [8, 7]])

In [29]:
np.roll(c,1,axis=0)

array([[7, 8],
       [1, 2],
       [3, 4],
       [5, 6]])

In [30]:
np.roll(c,2,axis=0)

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [31]:
np.roll(c,-2,axis=0)

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [32]:
# another concept 
arr1

array([[1, 2, 2],
       [2, 2, 2],
       [2, 2, 1]])

In [33]:
arr2

array([[1, 1, 1],
       [2, 1, 1],
       [2, 1, 1]])

In [34]:
arr1+arr2

array([[2, 3, 3],
       [4, 3, 3],
       [4, 3, 2]])

In [35]:
arr1-arr2

array([[0, 1, 1],
       [0, 1, 1],
       [0, 1, 0]])

In [36]:
arr1*arr2

array([[1, 2, 2],
       [4, 2, 2],
       [4, 2, 1]])

In [37]:
arr1>arr2

array([[False,  True,  True],
       [False,  True,  True],
       [False,  True, False]])

In [38]:
# bitwise negetion 
~ arr1

array([[-2, -3, -3],
       [-3, -3, -3],
       [-3, -3, -2]])

In [39]:
# operation on numpy string array 
array1=np.array(["pw","skills"])

In [42]:
k=np.char.upper(array1)  # Return an array with the elements converted to uppercase. mans convert into a uppercase


In [43]:
k

array(['PW', 'SKILLS'], dtype='<U6')

In [45]:
np.char.lower(k) # convert into a lowercase

array(['pw', 'skills'], dtype='<U6')

In [47]:
np.char.capitalize(array1) # Return a copy of `a` with only the first character of each element capitalized. Means each word every character is capital

array(['Pw', 'Skills'], dtype='<U6')

In [49]:
# mathmatical finction 
arr1

array([[1, 2, 2],
       [2, 2, 2],
       [2, 2, 1]])

In [51]:
np.sin(arr1) # sin returns the sin value of these value 

array([[0.84147098, 0.90929743, 0.90929743],
       [0.90929743, 0.90929743, 0.90929743],
       [0.90929743, 0.90929743, 0.84147098]])

In [52]:
np.cos(arr1)

array([[ 0.54030231, -0.41614684, -0.41614684],
       [-0.41614684, -0.41614684, -0.41614684],
       [-0.41614684, -0.41614684,  0.54030231]])

In [57]:
np.tan(arr1)

array([[ 1.55740772, -2.18503986, -2.18503986],
       [-2.18503986, -2.18503986, -2.18503986],
       [-2.18503986, -2.18503986,  1.55740772]])

In [63]:
np.log10(arr1) # log10 and log2 is possible

array([[0.     , 0.30103, 0.30103],
       [0.30103, 0.30103, 0.30103],
       [0.30103, 0.30103, 0.     ]])

In [64]:
np.log2(arr1)

array([[0., 1., 1.],
       [1., 1., 1.],
       [1., 1., 0.]])

In [66]:
np.exp(arr1) # it returns the exponential value 

array([[2.71828183, 7.3890561 , 7.3890561 ],
       [7.3890561 , 7.3890561 , 7.3890561 ],
       [7.3890561 , 7.3890561 , 2.71828183]])

In [68]:
np.power(arr1,2)  # it returns the power here we give 2 so it claculate 2 's power ,syntax:  np.power(array_name,num)

array([[1, 4, 4],
       [4, 4, 4],
       [4, 4, 1]], dtype=int32)

In [69]:
np.power(arr1,3)

array([[1, 8, 8],
       [8, 8, 8],
       [8, 8, 1]], dtype=int32)

In [70]:
# it returns the max value of the array 
np.max(arr1)

2

In [71]:
# it returns the avg value 
np.mean(arr1)

1.7777777777777777

In [72]:
np.min(arr1)

1

In [73]:
# it returns the standard deviation 
np.std(arr1)

0.41573970964154905

In [74]:
# variance
np.var(arr1)

0.1728395061728395

In [75]:
# you also subtracr this way 
np.subtract(arr1,arr2)

array([[0, 1, 1],
       [0, 1, 1],
       [0, 1, 0]])

In [78]:
np.multiply(arr1,arr2)

array([[1, 2, 2],
       [4, 2, 2],
       [4, 2, 1]])

In [80]:
np.mod(arr1,arr2)# return element wise remender  here all are zero bexause arr1 and arr2 has same element in same position 

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [81]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.        ]])

In [82]:
np.sqrt(arr2)

array([[1.        , 1.        , 1.        ],
       [1.41421356, 1.        , 1.        ],
       [1.41421356, 1.        , 1.        ]])

In [85]:
# sorting and searching the array element 
e=np.array([5,6,1,2,9])
np.sort(e) # Return a sorted copy of an array.

array([1, 2, 5, 6, 9])

In [87]:
n=np.searchsorted(e,4)  # Find indices where elements should be inserted to maintain order.meana this function a new element that we want to push and make it is sorted way and at the end it returns the index where the element push  

In [88]:
n

4

In [90]:
e=np.array([5,6,1,2,0,0,0,0,0,9])

In [91]:
np.count_nonzero(e)

5

In [95]:
e[e>0]

array([5, 6, 1, 2, 9])

In [99]:
np.extract(e>0,e)

array([5, 6, 1, 2, 9])

In [100]:
e.byteswap()  # Swap the bytes of the array elements


array([ 83886080, 100663296,  16777216,  33554432,         0,         0,
               0,         0,         0, 150994944])

In [101]:
import numpy.matlib as nm

In [102]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [104]:
nm.ones((3,3))

matrix([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [106]:
# if you want to return the determinant then 
nm.linalg.det(arr1)   # syntax: .linalg(means linear algebra ).det(means determinant)(array name) >>>> .linalg.det(array_name)

2.0

In [107]:
nm.linalg.det(arr2)

0.0

In [110]:
# inverse
nm.linalg.inv(arr1)  # if your diterminant is zero then you cannot calculate the inverse of the matrix 

array([[-1. ,  1. ,  0. ],
       [ 1. , -1.5,  1. ],
       [-0. ,  1. , -1. ]])

In [111]:
# solve the problem by using linear algebra 
# 7x +3y -5z=2
# 9x + 4y -2z =8
# 11x -4y+24z=28
# for solving this equation 
# step 1:
a=np.array([[7,3,-5],[9,4,-2],[11,-4,24]])

In [112]:
a

array([[ 7,  3, -5],
       [ 9,  4, -2],
       [11, -4, 24]])

In [114]:
# step 2 :
b=np.array([2,8,28])

In [115]:
b

array([ 2,  8, 28])

In [116]:
# here we see x ,y ,z value 
np.linalg.solve(a,b)

array([0.50331126, 1.45695364, 1.17880795])