##  Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [1]:
import numpy as np
a=np.random.randint(1,100,(3,3))

In [2]:
a

array([[91, 54, 12],
       [94, 95, 79],
       [ 7, 61, 70]])

In [8]:
# interchange means transpose 
a.T

array([[91, 94,  7],
       [54, 95, 61],
       [12, 79, 70]])

In [9]:
a[::-1]

array([[ 7, 61, 70],
       [94, 95, 79],
       [91, 54, 12]])

## 2.Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [10]:
a1=np.array([1,2,3,4,5,6,7,8,9,10])
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
a2=a1.reshape((2,5))

In [13]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [15]:
a2.reshape((5,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

## 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 arr

In [18]:

random_array = np.random.rand(4, 4)
bordered_array = np.pad(random_array, pad_width=1, mode='constant', constant_values=0)

bordered_array


array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.05012441, 0.77507858, 0.67432291, 0.85977679,
        0.        ],
       [0.        , 0.46405078, 0.45111703, 0.40440519, 0.53509075,
        0.        ],
       [0.        , 0.22615828, 0.99423095, 0.45761913, 0.53226732,
        0.        ],
       [0.        , 0.68812284, 0.51625008, 0.26353821, 0.7382625 ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

## 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [21]:
b=np.arange(10,65,5)

In [22]:
b

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

## 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [23]:
c=['python', 'numpy', 'pandas']
np.char.upper(c)

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [24]:
# lower case 
np.char.lower(c)

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [25]:
np.char.title(c)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [26]:
np.char.capitalize(c)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

## 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [27]:

words_array = np.array(["apple", "banana", "cherry", "date"])

# Insert a space between each character of every word
spaced_words_array = np.array([' '.join(word) for word in words_array])

spaced_words_array


array(['a p p l e', 'b a n a n a', 'c h e r r y', 'd a t e'], dtype='<U11')

## 7.Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [28]:

array1 = np.array([[10, 20], [30, 40]])
array2 = np.array([[1, 2], [3, 4]])

addition = array1 + array2


subtraction = array1 - array2


multiplication = array1 * array2


division = array1 / array2




In [29]:
addition

array([[11, 22],
       [33, 44]])

In [30]:
subtraction

array([[ 9, 18],
       [27, 36]])

In [31]:
multiplication

array([[ 10,  40],
       [ 90, 160]])

In [32]:
division

array([[10., 10.],
       [10., 10.]])

## 8.Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [33]:
identity=np.eye(5,5,dtype=int)

In [34]:
identity

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [35]:
diagonal=np.diag(identity)

In [36]:
diagonal

array([1, 1, 1, 1, 1])

## 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in 
this array

In [37]:

def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True
random_array = np.random.randint(0, 1000, 100)


prime_numbers = [num for num in random_array if is_prime(num)]

random_array, prime_numbers


(array([460, 200, 110, 611, 300, 782, 401, 727,  62, 362, 451, 993, 284,
        455, 881, 942, 549, 883, 551,  64, 799, 558,  19, 307, 669, 927,
        838, 448, 348, 745, 242, 186, 485, 446, 341, 645, 144, 987, 441,
        942, 861, 285, 521, 785, 657, 624, 797, 191,  60, 634, 123, 357,
         36, 804, 418, 223, 515, 721, 894, 923, 258, 787, 949, 826, 874,
         98, 818, 167, 772, 926, 382, 276, 484, 556, 188, 401,  59, 791,
        261, 504, 994, 170, 852, 898, 855, 823, 662, 558, 726, 944, 145,
        590, 854, 242, 169, 470, 844, 570, 958, 853]),
 [401,
  727,
  881,
  883,
  19,
  307,
  521,
  797,
  191,
  223,
  787,
  167,
  401,
  59,
  823,
  853])

## 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages

In [38]:

daily_temperatures = np.random.randint(15, 35, 30)  # Temperatures between 15°C and 35°C

# Split the array into weeks (4 full weeks + 2 extra days)
weeks = np.split(daily_temperatures[:28], 4)  # First 4 weeks (7 days each)
last_week = daily_temperatures[28:]           # Last week (2 extra days)

# Calculate weekly averages
weekly_averages = [np.mean(week) for week in weeks]
weekly_averages.append(np.mean(last_week))  # Add average for the last week

daily_temperatures, weekly_averages


(array([21, 18, 33, 23, 29, 19, 24, 20, 18, 23, 34, 27, 17, 21, 17, 17, 15,
        24, 16, 31, 30, 23, 16, 21, 25, 15, 31, 29, 17, 30]),
 [23.857142857142858,
  22.857142857142858,
  21.428571428571427,
  22.857142857142858,
  23.5])